name: CI

on:
  push:
  pull_request:
    types: [opened edited reopened review_requested]

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: make
        run: make -j8

  build-debian-old:
    runs-on: ubuntu-latest
    container: debian:oldoldstable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: make
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential
          make -j8

  build-macos-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: make
        run: make -j8

  build-32bit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: make
        run: |
          sudo apt-get update && sudo apt-get install -y libc6-dev-i386
          make -j8
